### ISSUE TITLE
Make sure prefix doesn't lead to double dash

### ISSUE THREAD

**Issue by tbpg** [googleapis/docuploader#51]
If you specify a `destination-prefix` that ends in a `-`, `docuploader` adds another `-` after it, leading to something like `docfx--my-package`.

`docuploader` should only add a `-` if there isn't one already.

https://github.com/googleapis/docuploader/blob/943325248f69aa072d796e25a887887c21f00211/docuploader/__main__.py#L131-L132

**Comment by eaball35** [comment]
Fixed with #52
